# Generated by Django 3.1.1 on 2020-10-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=120)),
                ('Last_name', models.CharField(max_length=120)),
                ('age', models.IntegerField(default=16)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('job', models.CharField(max_length=70)),
            ],
        ),
    ]
