# Generated by Django 3.1.1 on 2020-10-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_signup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='image',
            field=models.ImageField(upload_to='users/'),
        ),
    ]
